import { capitalize } from '@draw-house/common/dist/utils';
import { RouteResponse } from '@draw-house/common/dist/zod/routes/floorPlanImage/scan';
import { floorPlanRecognitionTimeoutInMinutes } from '@draw-house/common/dist/constants';
import { PositiveInteger } from '@draw-house/common/dist/brands';
import type { CustomModelsStore, GlobalSettingsStore, SlideUpMenuLvl2Store } from './zustand';
import { getWallType } from './utils/getWallType';
import { TooltipProps } from './components/Tooltip';

export const lang = {
  cabinet: {
    myProjects: 'My Projects',
    myTeam: 'My Team',
    billing: 'Billing',
    billingSubtitle: 'Manage your billing and payment details.',
    support: 'Support',
    account: 'Account',
    createDrawing: 'Create New',
    signup: 'Sign Up',
    logout: 'Log Out',
    startWithATemplate: 'Start With a Template',
    recentProjects: 'Recent Projects',
    emptyProjectsSuggestion: 'Create Your First Project',
    rename: 'Edit Name',
    delete: 'Delete',
    projectSuccessfullyDeleted: 'Project was successfully deleted.',
    projectDeletingError: 'Something went wrong during project deleting.',
    guestProfile: 'Guest Profile',
    sureForLogout: 'Do you want to log out?',
    logIn: 'Log in',
    logInSuggestion: 'Sign In to Unlock More Features',
    sureForProjectDeleting: {
      title: 'Are you sure you want to completely delete the project?',
      description: "This action can't be reverted. Every link of this project you shared with someone will no longer be available to access.",
    },
    howCanWeHelp: 'How can we help you?',
    subject: 'Subject',
    requiredField: 'The field is required.',
    emailSent: 'Your email is successfully sent.',
    emailSentError: 'Something went wrong during email sending.',
  },
  billing: {
    subscriptionOverview: 'Subscription Overview',
    usageSummary: 'Usage Summary',
    storageUsage: 'Storage usage',
    aiCapabilities: 'AI Capabilities',
    credits: {
      singular: 'credit',
      plural: 'credits',
    },
    paymentStatusProcessing: 'Payment method is processing. Check status later.',
    enterCardDetails: 'Enter Card Details',
    paymentMethod: 'Payment Method',
    paymentMethodSubtitle: 'Change how you pay for your plan',
    cancel: 'Cancel',
    saving: 'Saving...',
    saveCard: 'Save Card',
    paymentInfo: 'Payment Info',
    primary: 'Primary',
    change: 'Change',
    expiry: 'Expiry',
    currentPlanSection: {
      title: 'Current Plan',
      cancelButtonLabel: 'Cancel',
      upgradePlan: 'Upgrade plan',
      tryTeams: 'Try teams',
      changePlan: 'Change plan',
      expires: 'Expires',
      cancelSubscriptionTitle: 'Are you sure you want to cancel your subscription',
      cancelSubscriptionText: 'Your plan stays active until the end of the current period but won’t renew next month.',
      cancelSubscriptionGoBackButton: 'Go back',
      cancelSubscriptionCancelButton: 'Cancel subscription',
    },
  },
  buyDialog: {
    title: 'Upgrade your account',
    text: 'Buy a subscription to get an access to advanced features',
    buy: 'Buy',
  },
  account: {
    accountSettings: 'Account Settings',
    fullName: 'Full name',
    email: 'Email',
    changeName: 'Change Name',
    changeEmail: 'Change Email',
    changePassword: 'Change Password',
    deleteAccount: 'Delete account',
    wantToDelete: 'Do you want to delete your account?',
    cannotBeReserved: 'This action cannot be reversed.',
    enterPasswordConfirm: 'Enter password to confirm.',
    password: 'Password',
    successfullyDeleted: 'Account has been successfully deleted',
    deleteError: 'Error in deleting account',
    checkEmail: 'Check your new email',
    receiveConfirmationCode: 'You will receive a confirmation link on your new email',
    newName: 'New Name',
    newEmailAddress: 'New Email address',
    passwordChanged: 'Password has been successfully changed',
    oldPassword: 'Old Password',
    newPassword: 'New Password',
    repeatNewPassword: 'Repeat New Password',
    differentPasswords: 'Passwords are different',
  },
  confirm: 'Confirm',
  cancel: 'Cancel',
  send: 'Send',
  exit: 'Exit',
  search: 'Search',
  import: 'Import',
  importModel: {
    dragOrUploadObjects: 'Drag or Upload Objects',
    uploadObjectsFromFiles: 'Upload Objects from Files',
    successfullyUploaded: 'Successfully uploaded.',
    fileIsEmpty: 'File is empty.',
    supportedFormats: 'Supported formats',
    name: 'Name',
    loginToUnlockImport: 'Sign In to Unlock Import',
    addNew: 'Add New',
  },
  somethingWentWrong: 'Something went wrong.',
  notSavedProject: {
    sureToGoBack: (name: string) => `Do you want to save the project "${name}"?`,
    sureToGoBackGuest: (name: string) => `Do you want to log in and save the project "${name}"?`,
    saveAndExit: 'Save and exit',
  },
  notLoggedInGuest: 'You are not logged in. To save projects you need to log in first.',
  wallTypes: {
    exterior: 'Exterior wall',
    interior: 'Interior wall',
  } as const satisfies Record<ReturnType<typeof getWallType>, string>,
  slideUpMenus: {
    globalSettings: {
      title: 'Project settings',
      language: 'Language',
      languageValue: 'English',
      projectName: 'Project name',
      outlines: 'Outlines',
      outlinesSettings: {
        depthBias: 'Depth Bias',
        depthMultiplier: 'Depth Multiplier',
        normalBias: 'Normal Bias',
        normalMultiplier: 'Normal Multiplier',
        outlineColor: 'Outline Color',
        debugVisualize: 'Debug Visualize',
      },
      backgroundGrid: 'Background grid',
      zoomToSelection: 'Zoom to selection',
      gridSpacing: 'Grid cell size',
      snapDistance: 'Snap distance',
      snapConditions: 'Snap Conditions',
      snapConditionsValue: 'Grid Snap, End S...',
      viewSettingsValue: 'Landscape textures...',
      autoGeneratedRoofStyle: 'Auto Generated Roof Style',
      defaultWallThickness(wallType: ReturnType<typeof getWallType>) {
        return `${({
          exterior: 'Ext.',
          interior: 'Int.',
        } as const satisfies Record<typeof wallType, string>)[wallType]} Wall Thickness` as const;
      },
      measurementSystem: {
        title: 'Measurements',
        options: {
          metric: 'M, cm',
          imperial: 'F, inch',
        } as const satisfies Record<GlobalSettingsStore['measurementSystem'], string>,
      },
    },
    snapSettings: {
      wallEnd: 'End Snap',
      snapToWallLine: 'Snap to Wall Line',
      grid: 'Grid Snap',
      axis: 'Axis Lock Snap',
    },
    associatedObjects: {
      title: 'Choose an element',
    },
    wallSettings: {
      title: 'Wall Settings',
      name: 'Name',
      streetFacing: 'Street Facing',
      roomFacing: 'Room Facing',
      length: 'Length',
      applyToAll: (
        e: Extract<SlideUpMenuLvl2Store['slideUpMenuLvl2'], { type: 'wallAppearance' }>['applyToAll']['type'],
        type: 'street' | 'room',
      ) => ({
        sameFaceWallFaces: ({
          street: 'Street Facing Sides',
          room: 'Room Facing Sides',
        } satisfies Record<typeof type, string>)[type],
        sameFaceSameLevelWallFaces: ({
          street: 'Same Level Street Facing Sides',
          room: 'Same Level Room Facing Sides',
        } satisfies Record<typeof type, string>)[type],
        sameFaceSameSpaceWallFaces: ({
          street: 'Same Space Street Facing Sides',
          room: 'Same Space Room Facing Sides',
        } satisfies Record<typeof type, string>)[type],
      } satisfies Record<typeof e, string>)[e],
    },
    wallFurnitureSettings: {
      title: <T extends string>(e: T) => `${capitalize(e)} Settings` as const,
      flipHorizontal: 'Flip horizontal',
      mirror: 'Mirror',
      distanceToCeiling: 'Height from ceiling',
      distanceToFloor: 'Height from floor',
      applyToAll: (e: Extract<SlideUpMenuLvl2Store['slideUpMenuLvl2'], { type: 'wallFurnitureAppearance' }>['applyToAll']['type']) => ({
        sameWallFurnitures: 'Same models',
        sameLevelSameWallFurnitures: 'Same level same models',
      } satisfies Record<typeof e, string>)[e],
    },
    roofDormerSettings: {
      title: 'Dormer Settings',
      dormerType: 'Dormer Type',
    },
    customModelSettings: {
      title: (category: string) => `${category} Settings`,
      quickReplace: 'Quick Replace',
      commentName: 'Name',
      distanceToCeiling: 'Height from ceiling',
      distanceToFloor: 'Height from floor',
      applyToAll: (e: Extract<SlideUpMenuLvl2Store['slideUpMenuLvl2'], { type: 'customModelAppearance' }>['applyToAll']['type']) => ({
        sameLevelSameCustomModels: 'Same level same models',
        sameCustomModels: 'Same models',
      } satisfies Record<typeof e, string>)[e],
    },
    floorSettings: {
      title: 'Floor Settings',
      topMaterial: 'Top',
      edgeMaterial: 'Edge',
      bottomMaterial: 'Bottom',
      floorArea: 'Floor area',
      applyToAll: (e: Extract<SlideUpMenuLvl2Store['slideUpMenuLvl2'], { type: 'floorAppearance' }>['applyToAll']['type']) => ({
        sameLevelFloors: 'Same level floors',
        floors: 'Floors',
      } satisfies Record<typeof e, string>)[e],
    },
    ceilingSettings: {
      title: 'Ceiling Settings',
      heightFromBottom: 'Height from Level',
      topMaterial: 'Top',
      edgeMaterial: 'Edge',
      bottomMaterial: 'Bottom',
      name: 'Name',
      ceilingArea: 'Ceiling area',
      applyToAll: (e: Extract<SlideUpMenuLvl2Store['slideUpMenuLvl2'], { type: 'ceilingAppearance' }>['applyToAll']['type']) => ({
        sameLevelCeilings: 'Same level ceilings',
        ceilings: 'Ceilings',
      } satisfies Record<typeof e, string>)[e],
    },
    roofSettings: {
      title: 'Roof Settings',
      sharedRoofHint: 'This is a shared roof. To change Roof settings of one room, use space settings',
      roofType: 'Roof type',
      closedGableToggle: 'Closed gable',
      overhang: 'Overhang length',
      heightFromBase: 'Height from base',
      slope: 'Slope',
      topMaterial: 'Top',
      edgeMaterial: 'Fascia',
      bottomMaterial: 'Soffit',
      commentName: 'Name',
      rotate: 'Rotate',
      flip: 'Flip',
      roofArea: 'Roof area',
      applyToAll: (e: Extract<SlideUpMenuLvl2Store['slideUpMenuLvl2'], { type: 'roofAppearance' }>['applyToAll']['type']) => ({
        sameLevelRoofs: 'Same level roofs',
        roofs: 'Roofs',
      } satisfies Record<typeof e, string>)[e],
    },
    levelsSettings: {
      title: 'Levels',
      addNewLevel: 'Add new level',
      newLevel: 'New level',
      newLevelName: 'Level',
      levelSettings: 'Level settings',
      levelName: 'Level name',
      levelElevation: 'Floor level elevation',
      levelHeight: 'Floor height',
      deleteLevel: 'Delete the level',
      createLevel: 'Create a level',
      levelCreated: (e: string) => `${e} created.`,
    },
    visibilitySettings: {
      title: 'Hide/Show',
      unhideAll: 'Unhide all hidden items',
      showLandscapeTextures: 'Show environment (Land)',
      land: 'Land',
      showFloorTextures: 'Show floor textures in 2D',
      showRoofLinesIn2D: 'Show roof lines in 2D',
      showLabelsIn3DView: 'Show labels in 3D view',
      dimensions: 'Dimensions',
      insideDimensions: 'Inside',
      outsideDimensions: 'Outside',
      roofs: 'Roofs',
      walls: 'Walls',
      spaceNames: 'Spaces',
      exteriorWalls: 'Exterior walls',
      interiorWalls: 'Interior walls',
      floors: 'Floors',
      ceilings: 'Ceilings',
      construction: 'Construction',
      doors: 'Doors',
      windows: 'Windows',
      customModels: 'Custom models',
      columns: 'Columns',
      stairs: 'Stairs',
      assets2D: '2D Assets',
    },
    catalog: {
      title: 'Catalog',
      list: 'List',
      libraries: 'Libraries',
      category: 'Category',
      import: 'Import',
    },
    imageUpload: {
      title: 'Import',
    },
    replaceElementCatalog: {
      title: 'Replace element',
    },
    newCustomModelCategoryPicker: {
      title: 'Category',
    },
    spaceSettings: {
      title: 'Space settings',
      name: 'Name',
      spaceOptions: 'Space options',
      sharedBetween: 'shared between multiple spaces',
      hasUniqueRoof: 'Unique Roof',
      for: 'for',
      spaceArea: 'Space area',
    },
    stairSettings: {
      title: 'Stairs Settings',
      hint: 'Stairs hint',
      typeSection: 'Stairs Type',
      name: 'Name',
      width: 'Width',
      run: 'Run',
      rise: 'Rise',
      assembly: 'Assembly',
      topLanding: 'Top Landing',
      railingOrientation: 'Railing Orientation',
      stairs: 'Stairs',
      stringer: 'Stringer',
      railings: 'Railings',
      stringerLocation: 'Stringer location',
      railingsLocation: 'Railings location',
    },
    appearance: {
      title: 'Appearance',
      materials: 'Materials',
      textures: 'Textures',
      colorOverlay: 'Color Overlay',
      more: 'More',
      red: 'Red',
      green: 'Green',
      blue: 'Blue',
      transparency: 'Transparency',
      preview: 'Preview',
      compareToOriginal: 'Compare to Original',
      name: 'Name',
      compositeOperation: 'Composite operation',
      labels: {
        all: 'All',
        walls: 'Walls',
        floors: 'Floors',
        ceilings: 'Ceilings',
        roofs: 'Roofs',
        palette: 'Palette',
        spectrum: 'Spectrum',
        slider: 'Slider',
        recentTextures: 'Recent textures',
        recentColors: 'Recent colors',
        myTextures: 'My textures',
      },
    },
    asset2DSettings: {
      title: '2D Asset Settings',
      commentName: 'Name',
      transparency: 'Transparency',
      tilt: 'Tilt',
      location: (e: Extract<CustomModelsStore['customModels'][number], { type: 'asset-2d' }>['location']) => [
        'Location:',
        ({
          background: 'Background',
          foreground: 'Foreground',
        } satisfies Record<typeof e, string>)[e],
      ].join(' '),
    },
    aiTools: {
      title: 'AI Tools',
      generateFromPrompt: 'Generate from Prompt',
      preview: 'Preview',
      remake: 'Remake',
      create3D: 'Create 3D',
      select2DAsset: 'Select 2D asset',
      accuracy: 'Accuracy',
      wallFurnitureAccuracy: 'Wall furniture accuracy',
      accuracyTooltip: 'Higher accuracy takes longer time',
    },
    myAssets: {
      titleAll: 'My Assets',
      title2D: 'My 2D Assets',
    },
  },
  paywall: {
    title: 'Upgrade',
    description: 'Choose the subscription plan that’s right for you',
    yearlyTab: 'Yearly Billing',
    monthlyTab: 'Monthly Billing',
    paymentSuccess: 'Thank you for your payment! Redirecting back...',
    paymentFailure: 'Payment failed. Try again later. Redirecting back...',
  },
  baseLevel: 'Base level',
  area: 'Area',
  settings: 'Settings',
  isInvisible: 'Is invisible',
  thickness: 'Thickness',
  deleteItem: 'Delete the item',
  width: 'Width',
  height: 'Height',
  depth: 'Depth',
  length: 'Length',
  apply: 'Apply',
  none: 'None',
  type: 'Type',
  applyToAll: 'Apply to all',
  comingSoon: 'Coming soon!',
  continue: 'Continue',
  space: 'Space',
  roof: 'Roof',
  ceiling: 'Ceiling',
  floor: 'Floor',
  objectIdCopied: 'Object is copied to clipboard.',
  newProjectName: 'My project',
  spaceName: (e: PositiveInteger) => `Room ${e}`,
  roofName: (e: PositiveInteger) => `Roof ${e}`,
  ceilingName: (e: PositiveInteger) => `Ceiling ${e}`,
  stairName: (e: PositiveInteger) => `Stair ${e}`,
  wallName: (e: PositiveInteger) => `Wall ${e}`,
  material: (e: 'door' | 'window' | 'roof' | 'floor') => [
    ({
      door: 'Door',
      window: 'Window',
      roof: 'Roof',
      floor: 'Floor',
    } satisfies Record<typeof e, string>)[e],
    'Material/Color',
  ].join(' '),
  roofType: (e: 'none' | GlobalSettingsStore['defaultRoof']['type']) => ({
    none: 'No Roof',
    hip: 'Hip',
    'hip-with-all-gable-corners': 'Gable',
    flat: 'Flat',
    slanted: 'Slanted',
    wraparound: 'Wrap around',
  } satisfies Record<typeof e, string>)[e],
  quickTour: {
    previous: 'Previous',
    next: 'Next',
    finish: 'Finish',
  },
  floorPlanRecognition: {
    success: 'Created 3D from scan',
    error: {
      UnexpectedServerError: 'Something went wrong on the server.',
      WrongQueryParams: 'Wrong query parameters.',
      FileDownloadError: 'File download error.',
      FloorPlanRecognitionTimeoutReached: `Floor plan recognition timeout reached: ${floorPlanRecognitionTimeoutInMinutes} minutes.`,
      FloorPlanRecognitionFail: 'Floor plan recognition fail.',
    } satisfies Record<Extract<RouteResponse, { success: false }>['error']['type'], string>,
  },
  floorPlanAutoscale: {
    success: (ratio: number) => `Autoscale applied (ratio: ${ratio})`,
    error: 'Unable to calculate autoscale',
  },
  infoPanel: {
    placeholderTip: {
      title: 'App Hints',
      description: 'Explore the app and click on this button to get hints about relevant features.',
    },
  },
  firstPersonView: {
    title: 'First Person View',
    exit: 'Press Esc to exit',
    info: [
      'Click to enter FPV',
      'Move with WASD or arrows',
      'Look around with mouse',
    ],
  },
  liveHints: {
    autoPointer: {
      annotation: 'Select Mode',
      annotationDetails: 'Auto Switched',
    },
    emptySpaceClick: {
      annotation: 'Select Mode',
      annotationDetails: 'Switch to Draw Mode to Draw',
    },
    selectMode: {
      annotation: 'Select Mode',
      annotationDetails: 'Click on any object to modify',
    },
    straightLine: {
      annotation: 'Draw Mode',
      annotationDetails: 'Hold to draw walls',
    },
    multipleStraightLine: {
      annotation: 'Draw Mode',
      annotationDetails: 'Click to draw walls. Esc to Exit',
    },
    firstRoomCompleted: {
      annotation: 'Draw Mode',
      annotationDetails: 'Switch to 3D ↑ to view the 3D model',
    },
  },
  share: {
    popupTitle: 'Share the project',
    tabTitle: 'Share',
    publicLinkTitle: 'Public link',
    copyLinkButtonTitle: 'Copy link',
    copySuccessStatusText: 'Copied!',
  },
  export: {
    popupTitle: 'Export the project',
    tabTitle: 'Export',
    formatTitle: 'Format',
    exportButtonTitle: 'Export',
  },
  featureMap: {
    viewModesText: 'Draw walls and rooms in 2D, view and design building in 3D',
    wallModesText: 'Switch between draw and select modes',
    drawToolsText: 'Draw using paths, Single lines, Poly lines, and other tools',
    autoGenerationToolsText: 'Use or turn off auto generation options - wall, floor, roof, ceiling etc.',
    featureTipButtonText: 'View tips, tutorials, and more',
  },
  hotkeys: {
    globalTitle: 'Global Keys',
    showHotkeys: 'Show Hotkeys, Help',
    deleteSelected: 'Delete selected object',
    abandonAction: 'Abandon current action',
    copy: 'Copy',
    paste: 'Paste',
    switch2D3D: 'Switch between 2D/3D',
    noGridSnap: 'Invert Grid Snap',
    noAxisSnap: 'Invert Axis Snap',
    noGridAndGridSnap: 'Invert Grid and Axis Snap',
    moveLvlUp: 'Move up one level',
    moveLvlDown: 'Move down one level',
    quickAccessTitle: 'Quick Access Objects',
    door: 'Door',
    window: 'Window',
    cameraTitle: 'Camera Controls',
    rotate: 'Rotate',
    pan: 'Pan',
    zoom: 'Zoom',
    zoomIn: 'Zoom in',
    zoomOut: 'Zoom out',
    resetCamera: 'Reset camera',
    walkTitle: 'Walk Controls',
    walk: 'Walk',
    look: 'Look',
    unselectObject: 'Unselect Object',
  },
  paymentPlans: {
    month: 'month',
    seat: 'seat',
    yearlyPrice: (e: number) => `($${e} Yearly)`,
    yourCurrentPlan: 'Your Current Plan',
    upgradeTo: (plan: string) => `Upgrade to ${plan}`,
    changeTo: (plan: string) => `Change to ${plan}`,
    discountPercentage: (e: number) => `${e}% Discount`,
    currentPlanAlert: "You're already using this plan",
    activePlanExistsAlert: 'You will be automatically changed to this plan when your current subscription expires',
    free: {
      title: 'Free',
      description: 'Explore basic features',
      price: 'Free',
      featuresTitle: 'Included features:',
      features: [
        '3 Active projects',
        'Community support',
        'Basic models and textures',
        '2 Levels',
        'Export to PNG',
        '10 AI Credits(Coming Soon)',
      ],
    },
    professional: {
      description: 'Enhance your work',
      featuresTitle: 'Includes all Free Plan features and:',
      features: [
        '10 Active projects',
        'Email Support',
        'Premium models and textures',
        'Unlimited levels',
        'Export PNG, GLB, GLTF, etc.',
        'Import 2D and 3D assets',
        '100 AI Credits(Coming Soon)',
      ],
    },
    team: {
      description: 'Expand with clients and teams',
      featuresTitle: 'Includes all Professional Plan features and:',
      features: [
        '10 Active Projects per seat',
        'Real time collaboration ',
        'Comments and feedback',
        'Create & share an unlimited amount of projects',
      ],
    },
  },
  tooltips: {
    wallCreationButton: {
      title: 'Draw Spaces',
      description: 'Draw to create rooms and spaces',
      hotkey: 'D',
    },
    pointerModeButton: {
      title: 'Select',
      description: 'Select any object to change its properties',
      hotkey: 'S',
    },
    levelsMenuButton: {
      title: 'Levels',
      description: 'Levels allow you to manage vertical spaces',
      hotkey: 'L, Space',
    },
    visibilityMenuButton: {
      title: 'View Settings',
      description: 'Toggle visibility of project items',
      hotkey: 'V',
    },
    imageToolsButton: {
      title: '2D Image Tools',
      description: 'Import Floor plans for tracing, textures, or adding scenes',
      hotkey: 'F',
    },
    globalSettingsButton: {
      title: 'Preferences',
      description: 'Change units, default options, and more using settings',
      hotkey: 'P, T',
    },
    aiMenuButton: {
      title: 'AI',
      description: '3D Renders, Generate floor plans, Scan floor plans, Furnish rooms, possibilities are endless!',
      hotkey: 'A',
    },
    shareButton: {
      title: 'Share',
      description: 'Export various formats, or share a project link',
      hotkey: 'E',
    },
    catalogButton: {
      title: 'Catalog',
      description: 'Add items to your project from catalog or upload your own',
      hotkey: 'C, +',
    },
    wallDrawToolbarWall: {
      title: 'Auto generate Wall',
      description: 'Toggle on/off walls for your spaces',
    },
    wallDrawToolbarFloor: {
      title: 'Auto generate Floor',
      description: 'Toggle on/off auto generating floor for completed spaces',
    },
    wallDrawToolbarRoof: {
      title: 'Auto generate Roof',
      description: 'Toggle on/off auto generating roof for completed spaces',
    },
    wallDrawToolbarCeiling: {
      title: 'Auto generate Ceiling',
      description: 'Toggle on/off auto generating ceiling for completed spaces',
    },
    switchViewModeToWalkthrough: {
      title: 'Walk Mode',
      description: 'Walk using WASD keys and mouse for camera. Esc to exit.',
      hotkey: 'W',
    },
    toolbarClose: {
      title: 'Close',
      hotkey: 'Esc',
    },
    toolbarBack: {
      title: 'Back',
    },
    toolbarSettings: {
      title: 'Settings',
    },
    toolbarDuplicate: {
      title: 'Duplicate',
    },
    toolbarAddDoorOrWindow: {
      title: 'Add door or window',
    },
    toolbarAddDormer: {
      title: 'Add dormer',
    },
    toolbarGableDormer: {
      title: 'Gable Dormer',
    },
    toolbarHipDormer: {
      title: 'Hip Dormer',
    },
    toolbarShedDormer: {
      title: 'Shed Dormer',
    },
    toolbarMove: {
      title: 'Move',
    },
    toolbarChangeOrientation: {
      title: 'Change orientation',
    },
    toolbarReplace: {
      title: 'Replace',
    },
    toolbarChangeGableCorner: {
      title: 'Change gable corner',
    },
    toolbarRotateCounterclockwise: {
      title: 'Rotate counterclockwise',
    },
    toolbarRotateClockwise: {
      title: 'Rotate clockwise',
    },
    toolbarRotate: {
      title: 'Rotate',
    },
    toolbarQuickRotate: {
      title: 'Quick Rotate',
    },
    toolbarScale: {
      title: 'Scale',
    },
    toolbarTapeMeasure: {
      title: 'Tape measure',
    },
    toolbarHide: {
      title: 'Hide',
    },
    toolbarSelectItem: {
      title: 'Select item',
    },
    toolbarDelete: {
      title: 'Delete',
      hotkey: 'Del',
    },
  } as const satisfies Record<string, TooltipProps['content']>,
} as const;
