import { ButtonOptionsRow, FloatingMenu, IconPickerRow, InitialMenuWrapper, MainButton, MenuItem, MenuSection, SlideUpMenu, TextField } from '@draw-house/ui/dist/components';
import { useEffect, useState } from 'react';
import { isNull } from '@arthurka/ts-utils';
import { lang } from '../lang';
import { setMeasurementSystemFromInitialSettings, useAppPage, useCreationModeConfig, useFeatureMapState, useGlobalSettings, useIsDesktopMenu } from '../zustand';
import { Animations } from './animations';
import { clearZustandStore, detectActiveInfoPanelFeature, dispatchInfoPanelEvent } from '../utils';
import { useLoadAppRunNecessaryData } from '../customHooks/useLoadAppRunNecessaryData';
import { LocalStorageService } from '../services/LocalStorageService';

const InitialSettingsWrapper: React.FCWithChildren = ({ children }) => {
  const { isDesktopMenu } = useIsDesktopMenu();
  const [isOpened, setIsOpened] = useState(false);

  const commonProps = {
    title: lang.slideUpMenus.globalSettings.title,
    async onClose() {
      useAppPage.setState({ appPage: 'my-projects' });
      await clearZustandStore();
    },
  };

  useEffect(() => {
    setIsOpened(true);
  }, []);

  return (
    isDesktopMenu === false
      ? (
        <SlideUpMenu {...commonProps} opened={isOpened}>
          {children}
        </SlideUpMenu>
      )
      : (
        <Animations.fade>
          <InitialMenuWrapper>
            <FloatingMenu {...commonProps}>
              {children}
            </FloatingMenu>
          </InitialMenuWrapper>
        </Animations.fade>
      )
  );
};

export const InitialSettings: React.FC = () => {
  useLoadAppRunNecessaryData();

  const projectName = useGlobalSettings(s => s.projectName);
  const measurementSystem = useGlobalSettings(s => s.measurementSystem);
  const defaultRoof = useGlobalSettings(s => s.defaultRoof);

  useEffect(() => {
    const activeFeature = detectActiveInfoPanelFeature();

    if(!isNull(activeFeature)) {
      dispatchInfoPanelEvent(activeFeature);
    }
  }, []);

  return (
    <InitialSettingsWrapper>
      <MenuItem divider paddingHorizontal>
        <TextField
          type='text'
          label={lang.slideUpMenus.globalSettings.projectName}
          size='lg'
          value={projectName}
          onChange={projectName => {
            useGlobalSettings.setState({ projectName });
          }}
        />
      </MenuItem>
      <MenuItem divider>
        <ButtonOptionsRow
          label={lang.slideUpMenus.globalSettings.measurementSystem.title}
          options={[
            {
              text: lang.slideUpMenus.globalSettings.measurementSystem.options.metric,
              selected: measurementSystem === 'metric',
              onClick() {
                setMeasurementSystemFromInitialSettings('metric');
              },
            },
            {
              text: lang.slideUpMenus.globalSettings.measurementSystem.options.imperial,
              selected: measurementSystem === 'imperial',
              onClick() {
                setMeasurementSystemFromInitialSettings('imperial');
              },
            },
          ]}
        />
      </MenuItem>
      <MenuSection
        title={lang.slideUpMenus.globalSettings.autoGeneratedRoofStyle}
        type='static'
        divider='content'
        titleVariant='pale'
      >
        <MenuItem>
          <IconPickerRow
            items={[
              {
                id: 'hip-with-all-gable-corners',
                icon: 'gableRoof',
                state: defaultRoof.isVisible === true && defaultRoof.type === 'hip-with-all-gable-corners' ? 'active' : 'default',
                label: lang.roofType('hip-with-all-gable-corners'),
              },
              {
                id: 'hip',
                icon: 'hipRoof',
                state: defaultRoof.isVisible === true && defaultRoof.type === 'hip' ? 'active' : 'default',
                label: lang.roofType('hip'),
              },
              {
                id: 'wraparound',
                icon: 'wraparoundRoof',
                state: defaultRoof.isVisible === true && defaultRoof.type === 'wraparound' ? 'active' : 'default',
                label: lang.roofType('wraparound'),
              },
              {
                id: 'slanted',
                icon: 'slantedRoof',
                state: defaultRoof.isVisible === true && defaultRoof.type === 'slanted' ? 'active' : 'default',
                label: lang.roofType('slanted'),
              },
              {
                id: 'flat',
                icon: 'flatRoof',
                state: defaultRoof.isVisible === true && defaultRoof.type === 'flat' ? 'active' : 'default',
                label: lang.roofType('flat'),
              },
              {
                id: 'none',
                icon: 'noRoof',
                state: defaultRoof.isVisible === false ? 'active' : 'default',
                label: lang.roofType('none'),
              },
            ]}
            onClick={type => {
              const { creationModeConfig } = useCreationModeConfig.getState();

              switch(type) {
                case 'none':
                  useGlobalSettings.setState({
                    defaultRoof: {
                      ...defaultRoof,
                      isVisible: false,
                    },
                  });
                  useCreationModeConfig.setState({
                    creationModeConfig: {
                      ...creationModeConfig,
                      isCeilingVisible: false,
                    },
                  });

                  break;
                case 'hip-with-all-gable-corners':
                case 'hip':
                case 'flat':
                case 'slanted':
                case 'wraparound':
                  useGlobalSettings.setState({
                    defaultRoof: {
                      isVisible: true,
                      type,
                    },
                  });
                  useCreationModeConfig.setState({
                    creationModeConfig: {
                      ...creationModeConfig,
                      isCeilingVisible: true,
                    },
                  });

                  break;
                default:
                  ((e: never) => e)(type);
                  throw new Error('This should never happen. |xyv2d7|');
              }
            }}
          />
        </MenuItem>
      </MenuSection>
      <MenuItem paddingHorizontal>
        <MainButton
          text={lang.continue}
          width='fill'
          height='md'
          onClick={() => {
            useAppPage.setState({ appPage: 'planner' });

            const isQuickTourCompleted = LocalStorageService.quickTour.isCompleted.get();
            if(isQuickTourCompleted === true) {
              useFeatureMapState.setState({ featureMapState: 'show' });
            }
          }}
        />
      </MenuItem>
    </InitialSettingsWrapper>
  );
};
